os: windows
language: c

before_install:
  - choco upgrade cmake --pre
  - git clone https://github.com/libcheck/check.git
  # - git clone https://github.com/Snaipe/fmem.git
  # - git clone https://github.com/Loupi/peg.git
  # - git clone https://github.com/alex85k/wingetopt.git
  - cd check
  - mkdir build64
  - pushd build64
  - cmake -G "Visual Studio 15 2017" -A x64 ..
  - popd
  - cmake --build build64 --config Release

install:
  - mkdir build64 & pushd build64
  - cmake -G "Visual Studio 15 2017 Win64" ..
  - popd
  - cmake --build build64 --config Release
