os: windows
language: c

before_install:
  - choco upgrade cmake --pre
  # Build check
  - git clone https://github.com/libcheck/check.git
  - pushd check
  - printf 'cmake_policy(SET CMP0091 NEW)\nset(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")\n' | 
     cat - CMakeLists.txt > temp && mv temp CMakeLists.txt
  - mkdir build64
  - pushd build64
  - cmake -D BUILD_TESTING=0 -D CHECK_ENABLE_TESTS=0 -G "Visual Studio 15 2017" -A x64 ..
  - popd
  - cmake --build build64 --config Release
  - popd
  # Build fmem
  - git clone https://github.com/Snaipe/fmem.git
  - pushd fmem
  - printf 'cmake_policy(SET CMP0091 NEW)\nset(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")\n' | 
     cat - CMakeLists.txt > temp && mv temp CMakeLists.txt
  - mkdir build64
  - pushd build64
  - cmake -D BUILD_TESTING=0 -G "Visual Studio 15 2017" -A x64 ..
  - popd
  - cmake --build build64 --config Release
  - popd
  # build peg
  - git clone https://github.com/Loupi/peg.git
  - pushd peg
  - printf 'cmake_policy(SET CMP0091 NEW)\nset(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")\n' | 
     cat - CMakeLists.txt > temp && mv temp CMakeLists.txt
  - mkdir build64
  - pushd build64
  - cmake -G "Visual Studio 15 2017" -A x64 ..
  - popd
  - cmake --build build64 --config Release
  - popd
  # Build wingetopt
  - git clone https://github.com/alex85k/wingetopt.git
  - pushd wingetopt
  - printf 'cmake_policy(SET CMP0091 NEW)\nset(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")\n' | 
     cat - CMakeLists.txt > temp && mv temp CMakeLists.txt
  - mkdir build64
  - pushd build64
  - cmake -G "Visual Studio 15 2017" -A x64 ..
  - popd
  - cmake --build build64 --config Release
  - popd

install:
  - printf 'cmake_policy(SET CMP0091 NEW)\nset(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")\n' | 
     cat - CMakeLists.txt > temp && mv temp CMakeLists.txt
  - mkdir build64
  - pushd build64
  - cmake 
     -D CHECK_INCLUDE_DIR='C:/Users/travis/build/Loupi/libcypher-parser/check/build64/src' 
     -D CHECK_LIBRARY='C:/Users/travis/build/Loupi/libcypher-parser/check/build64/src/Release/check.lib' 
     -D COMPAT_LIBRARY='C:/Users/travis/build/Loupi/libcypher-parser/check/build64/lib/Release/compat.lib' 
     -D FMEM_INCLUDE_DIR='C:/Users/travis/build/Loupi/libcypher-parser/fmem/build64/gen' 
     -D FMEM_LIBRARY='C:/Users/travis/build/Loupi/libcypher-parser/fmem/build64/Release/fmem.lib' 
     -D GETOPT_INCLUDE_DIR='C:/Users/travis/build/Loupi/libcypher-parser/wingetopt/src' 
     -D GETOPT_LIBRARY='C:/Users/travis/build/Loupi/libcypher-parser/wingetopt/build64/Release/wingetopt.lib' 
     -D LEG_PROGRAM='C:/Users/travis/build/Loupi/libcypher-parser/peg/build64/Release/leg.exe' 
     -G 'Visual Studio 15 2017' -A x64..
  - popd
  - cmake --build build64 --config Release
